Repository kalviumcommunity/S82_BalaGiri_A_Capstone_DigitalDiary, pull requests merged in 2025-05, with the labels that each got.

#1 :)
  backend/server.js
Labels: Review effort 1/5

#2 Readme
  README.md
Labels: Review effort 1/5

#4 frontend and backend
  backend/uploads/1747206929442-166158359.png
  backend/uploads/1747206929446-50055626.mp3
  frontend/src/App.jsx
  frontend/src/Pages/Dairypage.jsx
  frontend/src/components/NewEntry.jsx
Labels: Review effort 3/5

#6 CRUD operation
  backend/.env
  backend/controllers/diaryController.js
  backend/middleware/multer.js
  backend/routes/diaryRoutes.js
  backend/server.js
  backend/uploads/audio/1747196799577-802070361.mp3
  backend/uploads/audio/1747206929446-50055626.mp3
  backend/uploads/photos/1747196799570-863798478.png
  backend/uploads/photos/1747206929442-166158359.png
  frontend/src/Pages/Dairypage.jsx
  frontend/src/components/NewEntry.jsx
Labels: Review effort 3/5

#7 Updatedreadme
  README.md
  backend/controllers/authController.js
  backend/middleware/auth.js
  backend/routes/diaryRoutes.js
  backend/server.js
  frontend/src/components/CalendarView.jsx
  frontend/src/components/NewEntry.jsx
Labels: Review effort 3/5

#9 Updated readme file
  README.md
Labels: Review effort 1/5

#11 :(
  README.md
  backend/.env
  backend/.gitignore
  backend/controllers/authController.js
  backend/controllers/diaryController.js
  backend/middleware/auth.js
  backend/routes/authRoutes.js
  backend/routes/diaryRoutes.js
  backend/server.js
  frontend/src/Pages/Dairypage.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/components/NewEntry.jsx
Labels: Review effort 4/5

#13 Created About.jsx
  frontend/src/Pages/About.jsx
Labels: Review effort 1/5

#12 done
  frontend/src/App.jsx
  frontend/src/Pages/Features.jsx
Labels: Review effort 2/5

#16 :(
  README.md
  backend/uploads/audio/audio-1747309807151-277116274.mp3
  backend/uploads/photos/photos-1747299409376-140515779.jpg
  backend/uploads/photos/photos-1747299424315-201966008.jpg
  backend/uploads/photos/photos-1747309807126-993015013.png
  backend/uploads/photos/photos-1747309894821-519851475.png
  capstone/Storage.bru
  capstone/bruno.json
Labels: Review effort 1/5
